# Generated by Django 5.0.6 on 2024-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expTracker', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='totalExpense',
            field=models.FloatField(default=0),
        ),
    ]
