# Generated by Django 5.0.6 on 2024-06-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expTracker', '0004_expense_totalexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='totalExpense',
        ),
    ]
